//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: gRPC-Client/imu.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Imu_ImuClient`, then call methods of this protocol to make API calls.
internal protocol Imu_ImuClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Imu_ImuClientInterceptorFactoryProtocol? { get }

  func send(
    _ request: Imu_ImuFrame,
    callOptions: CallOptions?
  ) -> UnaryCall<Imu_ImuFrame, Imu_Empty>

  func reset(
    _ request: Imu_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<Imu_Empty, Imu_Empty>
}

extension Imu_ImuClientProtocol {
  internal var serviceName: String {
    return "imu.Imu"
  }

  /// Unary call to Send
  ///
  /// - Parameters:
  ///   - request: Request to send to Send.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func send(
    _ request: Imu_ImuFrame,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imu_ImuFrame, Imu_Empty> {
    return self.makeUnaryCall(
      path: "/imu.Imu/Send",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendInterceptors() ?? []
    )
  }

  /// Unary call to Reset
  ///
  /// - Parameters:
  ///   - request: Request to send to Reset.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func reset(
    _ request: Imu_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imu_Empty, Imu_Empty> {
    return self.makeUnaryCall(
      path: "/imu.Imu/Reset",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeResetInterceptors() ?? []
    )
  }
}

internal protocol Imu_ImuClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'send'.
  func makeSendInterceptors() -> [ClientInterceptor<Imu_ImuFrame, Imu_Empty>]

  /// - Returns: Interceptors to use when invoking 'reset'.
  func makeResetInterceptors() -> [ClientInterceptor<Imu_Empty, Imu_Empty>]
}

internal final class Imu_ImuClient: Imu_ImuClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Imu_ImuClientInterceptorFactoryProtocol?

  /// Creates a client for the imu.Imu service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Imu_ImuClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

